### ISSUE TITLE
Misspelling on Slide 56 of the Week 1 Slides.

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#1]
The sentence "A word may be broken into separate tokens if it meaningful makes sense" seems to miss out "A word may be broken into separate tokens if it meaningful**ly** makes sense" on it.

See attached image for reference.

<img width="477" alt="Screenshot 2024-01-08 at 19 50 24" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/56546be7-0092-4bbe-963e-82d375b54358">

**Comment by jakelever** [comment]
Excellent. Thanks for submitting. That will be 1 point
