### ISSUE TITLE
Lecture 2 Slide 26 Typo

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#10]
Djokovic is misspelt. This was pointed out in class but wished to add here as a reminder, don't worry about points for this one :P

<img width="116" alt="Screenshot 2024-01-16 at 13 37 15" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/c2d0bdd0-ff8c-4bbe-bac1-288a6cf569c8">

**Comment by JacksonDam** [comment]
or do worry about points 😤

**Comment by jakelever** [comment]
Yep, thanks for reminding me. Still 1 point for being the first to report it
