### ISSUE TITLE
lab 2 

### ISSUE THREAD

**Issue by chloeyeo** [jakelever/textasdata_bugbounty#10]
![image](https://user-images.githubusercontent.com/73764849/214911891-6bc2a5d7-a64b-47d9-8eb3-e663e301c32d.png)

bug 1: If instance is not a dictionary, I think it was assumed we return size + sum(map(sizeof, obj) again instead of returning just size because sys.getsizeof(list) for example doesn't get the size of elements in list as well, but when we run it it somehow gets an even larger size than the list + elements in it, which is opposite to what was expected

bug(?) 2:![image](https://user-images.githubusercontent.com/73764849/214912479-590e6218-b27f-4a47-97dc-a2a052bb6b58.png)
This is not a bug but it works without the len(token_counts) so we can just do token_counts.most_common()

:)

**Comment by jakelever** [comment]
Nice catches. The sizeof function above does not work properly. I've fixed that (with a better answer from the [StackOverflow post](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python)). And the second one is also a bit of unnecessary code. 

So 3 for the first mistake as it doesn't work at all well and 1 for the second. 4 points total!
