### ISSUE TITLE
Lecture 8 slide 47 potential unsplit slide

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#100]
Not sure about this one since it's fairly simple, but you may have intended to split this slide into two (one with the answer, one without) since it is asking a question:

![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/4476ea8f-f81f-462e-b288-48790ffa8847)

**Comment by jakelever** [comment]
No, I hadn't planned on this being a question with a hidden part. Good thought though. So 0 points
