### ISSUE TITLE
Coursework spec Q3/Q4 sentence preposition

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#102]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/ff870588-c335-446f-909f-3d8b613cc901)

These two should probably use "performance on the" rather than "performance of the", which would also keep consistency with Q6.1.

**Comment by jakelever** [comment]
This is fairly minor but still worth fixing. 1 point
