### ISSUE TITLE
Coursework spec Q3 "development set"

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#103]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/bdda388a-cd8e-4df0-a424-1e6cf84cc80b)

I feel like "development set" here should be referring to "validation set" - still technically a correct name for a validation set but could confuse some people

**Comment by jakelever** [comment]
Yep. Nice one. This may have been confusing so 3 points
