### ISSUE TITLE
Lecture 9 slide 4 + slide 7 missing model name hyphens

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#104]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/3657e7e0-e8bc-463a-9e19-bb5a41716b9d)
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/a3e0e7dc-b96d-43e5-9801-2112b5a819b3)

A hyphen should probably be added on slides 4, 7 (e.g. GPT-2 not GPT2) to keep consistency with the other slides and with OpenAI.

**Comment by jakelever** [comment]
Yep. Fixed and 1 point
