### ISSUE TITLE
Lecture 9 Slide 7 Missing Accent

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#108]
Should be "raison d'être" with an accent over the 'e'.

<img width="318" alt="Screenshot 2024-03-04 at 18 51 10" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/cdcfbc72-28f8-4806-a9cc-e4939bec616a">

**Comment by jakelever** [comment]
Fixed. Thanks & 1 point
