### ISSUE TITLE
Lecture 10, slide 25 capitalization

### ISSUE THREAD

**Issue by GoldenZs3** [jakelever/textasdata_bugbounty#113]
On slide 25, the first sub-list is uncapitalized, while every other sublist (including the other one on the same slide) in the whole set of slides is capitalized. Would be nice to keep consistency.
![image](https://github.com/jakelever/textasdata_bugbounty/assets/68826158/cbddb2e3-029f-4313-bb0d-12c968f73036)

**Comment by jakelever** [comment]
Thanks for submitting
