### ISSUE TITLE
Slide 49 Incorrect Brackets

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#114]
The square brackets around '[CLS]' are incorrect, instead being '[CLS'].

<img width="1062" alt="Screenshot 2024-03-12 at 14 15 41" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/231f6d17-c2de-4c42-8b91-e2f61d84d220">

**Comment by jakelever** [comment]
Well spotted. Thanks for submitting!
