### ISSUE TITLE
Lecture 2 Slide 99 Typo

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#14]
I believe it should be "wide range _of_ tasks".

<img width="651" alt="Screenshot 2024-01-16 at 14 42 09" 
src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/e8f44717-16cb-48f9-b5fc-2acf9e828652">

**Comment by jakelever** [comment]
Agreed and fixed. Thanks. 1 point
