### ISSUE TITLE
Lab 3 - verb grammar

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#16]
A couple misspellings with the structure
> Write a function <func_name> that <...>, **verb** <...>.

e.g.:
> Write a **function** unigram_token_prob **that** given a token, the unigram counts and the total number of unigrams, **return** the probability of that token.

Should be `returns` instead of `return`.

[Cell 1](https://colab.research.google.com/drive/1LgQzO-Ttim0xvamlB-0AsfXADAyVdpAt#scrollTo=tf5-Ct4l1EOl)
[Cell 2](https://colab.research.google.com/drive/1LgQzO-Ttim0xvamlB-0AsfXADAyVdpAt#scrollTo=lQFdSOO01-Co)

**Comment by jakelever** [comment]
Fixed. Thanks. 2 points for 2 mistakes
