### ISSUE TITLE
Lecture 1, Slide 77

### ISSUE THREAD

**Issue by ezad99** [jakelever/textasdata_bugbounty#16]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/76674776/e63b9fc6-a508-4d50-b933-4ac3a33c8305)

should be "is the intersection"

**Comment by ezad99** [comment]
and |.| should be | | just to avoid confusion, though that might just be me

**Comment by jakelever** [comment]
Made it a bit clearer with |Z| instead. Let's say 1 point
