### ISSUE TITLE
Lab 3 - noun grammar

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#17]
> <...> On the other hand, we can't model **all** of the preceding **token** <...>

Should be `tokens` instead of `token`.

[Cell](https://colab.research.google.com/drive/1LgQzO-Ttim0xvamlB-0AsfXADAyVdpAt#scrollTo=dRslwUFqDn_t)

**Comment by jakelever** [comment]
Thanks. Fixed. 1 point
