### ISSUE TITLE
Lab 3 - math not imported

### ISSUE THREAD

**Issue by SamSJackson** [jakelever/textasdata_bugbounty#18]
Again, not sure if I have missed a cell to run or something.

During the unigram sequence model portion of the Colab notebook, we use math.log2 however math is not imported earlier on.

![image](https://user-images.githubusercontent.com/86316114/215755649-7ca47426-6265-4f70-98da-4a2ae5ebf6be.png)

**Comment by jakelever** [comment]
Yeah, I could see some confusion from this, though I'd have thought you would need `math` for the `unigram_sequence_logprob` function. I've added an `import math` to the previous cell for defining `unigram_sequence_logprob` just to make it clear. A fairly minor coding point but thank you for raising it. I think it's just 1 point.
