### ISSUE TITLE
Confusing Names on Moodle

### ISSUE THREAD

**Issue by JakeTrevor** [jakelever/textasdata_bugbounty#19]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/50667410/216386526-ba637739-c847-41f6-af1d-c488947b7440.png">

Included screenshot for course shedule table on moodle;

Lab 3 is Language modelling, lab 2 is Geometric similarity 

However, I got a bit confused when submitting because the lectures are one week ahead - and so it looks like lab 3 is on text classification, and lab 2 is on language modelling.

It would be useful if the labs als explicitly spelt out their topic in that section.

**Comment by jakelever** [comment]
Yep, that's a good point. I've put the names of the labs in so hopefully it's clearer. Thanks. I'll say 2 points as it was useful feedback on the main page
