### ISSUE TITLE
Lecture 3 inconsistent mixed usage between "modeling" and "modelling"

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#19]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/7b130c71-93ae-4434-bcff-ccd06618ed7a)
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/da270d68-5d6a-4a50-9352-f2120156f31a)

There are 23 occurrences of "modelling" and 4 occurrences of "modeling". These should be made consistent.

![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/680a67d2-abd1-4bb9-b9c4-a1988f44be83)
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/bd24797a-7241-4eeb-8c05-52edc63fb18c)

In addition, the title of the topic on Moodle uses "modeling".

**Comment by jakelever** [comment]
Yep, consistency is good. 1 point
