### ISSUE TITLE
Lab 3 - spelling issue

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#22]
[Link to cell](https://colab.research.google.com/drive/1LgQzO-Ttim0xvamlB-0AsfXADAyVdpAt#scrollTo=JOoet6sSEbKR)

> We will only store the entries that we observe; the rest **we can taken to be zero** or we can estimate their values using smoothing.

**Comment by jakelever** [comment]
Fixed. Thanks. 1 point
