### ISSUE TITLE
Lab 4 - Answer included for exercise

### ISSUE THREAD

**Issue by AnimatorOfSouls** [jakelever/textasdata_bugbounty#23]
The answer for the following exercise is already included in the code box.

"Exercise: Use [scikit-learn metrics functions](https://scikit-learn.org/stable/modules/model_evaluation.html) to calculate the accuracy, precision, recall and f1 scores of our earlier predictions labels_predicted against the actual labels labels_val."

![image](https://user-images.githubusercontent.com/33594615/217088708-d95509ae-b733-436b-8c91-728ec45a3107.png)

**Comment by jakelever** [comment]
Nice catch. Thank you. 3 points
