### ISSUE TITLE
Lab 4 - Incorrect stated F1 score

### ISSUE THREAD

**Issue by AnimatorOfSouls** [jakelever/textasdata_bugbounty#24]
In part "Changing the hyperparameters" the F1 score is supposedly meant to be 0.759, but when I run my code I get 0.752.  Since the code I use was correct in the previous section and only required that I change the tokenizer and the C value I believe the stated value is incorrect.

![image](https://user-images.githubusercontent.com/33594615/217095874-5a7df7db-27bc-4a16-a520-e7b8c5c11976.png)

**Comment by jakelever** [comment]
Great catch! I had accidentally run it with Spacy (the opposite of the instructions). I also get 0.752 when I don't make that mistake. 3 points
