### ISSUE TITLE
Lecture 5 - Spelling (+other) mistakes

### ISSUE THREAD

**Issue by AnimatorOfSouls** [jakelever/textasdata_bugbounty#25]
Slide 64: "Words that indicate topic" -> "Words that indicate a topic"
Slide 68: "Spot the corrupted word:" is italicised instead of bolded like the other headings on the slide (and also mysteriously missing the colon on the next slide).
Slide 97/102: "Zero-shot" is never actually explained despite using it as a heading.

**Comment by jakelever** [comment]
Excellent points

- Fixed the spelling mistake (1)
- Put in a name for the corrupted word task (1)
- Very good point here. Decided to rework the slides a bit to make things clear (4 for conceptual)

So 6 points total
