### ISSUE TITLE
Lecture 3 Duplicate Slide 15+16

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#26]
Seems that there are two of the same slide, at least in the copy I have downloaded today.
<img width="498" alt="Screenshot 2024-01-20 at 18 45 53" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/26f64d44-3424-447b-b804-81a85a3f6ff3">

**Comment by jakelever** [comment]
Thanks. I'd meant to hide the answer in the first one so that would have tripped me up. 3 points
