### ISSUE TITLE
Potential Missing Word in Lecture 3, Slide 6

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#27]
Could potentially use "The next word in a sequence" instead of just "Next word in a sequence".

<img width="221" alt="Screenshot 2024-01-23 at 13 15 19" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/db6725df-57b7-4d2a-8aaa-506fc98cf162">

**Comment by JacksonDam** [comment]
I would argue this to be acceptable - "zero article" in a numbered list
https://ell.stackexchange.com/a/177473

**Comment by jakelever** [comment]
Yeah, I won't fix this as stylistically I go for fewer words in bulletpoints. So 0 points.
