### ISSUE TITLE
Lecture 5 slide 71 pangram mistake?

### ISSUE THREAD

**Issue by KangarooWasp** [jakelever/textasdata_bugbounty#27]
I'm not sure if this qualifies as an error or not because you didn't actually say anything _incorrect_ as such, but what you wrote is probably not what you meant to write.

In slide 71 of lecture 5 you give "The quick brown fox **jumped** over the lazy dog." as an example of an English sentence.
I think you probably meant "The quick brown fox **jumps** over the lazy dog."? The latter is a common example of a pangram, featuring every letter in the English alphabet. The version found in the slide does not contain the letter 's'.

Admittedly, it doesn't really matter in this context whether or not the sentence is a pangram.

**Comment by jakelever** [comment]
Brilliant. Yeah, I think I've been using that incorrectly for a while now. Fixed and 2 points for the more "complex" spelling mistake
