### ISSUE TITLE
Double space Lecture 3 slide 100

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#28]
<img width="459" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/fa0f6146-2471-4860-a235-6a2a46da46ae">

sorry :(

**Comment by MrSpuddy** [comment]
No you aren't

**Comment by jakelever** [comment]
I really need to search for double-spaces before I release slides. Fixed. 1 point
