### ISSUE TITLE
Lab 4 - confusing variable naming

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#28]
[Link to cell](https://colab.research.google.com/drive/12WU24SwqQlDmHiY841QN9-K_4goBxhWY#scrollTo=1FOtIce5B3D9)
>  Use the existing classifier `clf` to make predictions on the training vectors `X_train` and calculate <...>

Variable names `clf` and `X_train` were not defined before, and naming them in this way was not hinted or enforced for earlier tasks. Got slightly confused - would probably remove the variable names altogether.

**Comment by jakelever** [comment]
Agreed. Fixed and 1 point
