### ISSUE TITLE
Lecture 3 slide 23, slide 89 mixed use between "coloured" and "colored"

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#29]
<img width="95" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/9582b2e9-c424-4d2e-9b6a-7f173d9a99cb">
<img width="79" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/113c6a0b-d923-422b-b451-45b4b837ae13">

Slide 23 (top) uses "coloured', slide 89 (bottom) uses "colored"

**Comment by jakelever** [comment]
Yep, consistency good. 1 point
