### ISSUE TITLE
Typo in lab 2 - Zipf's law definition

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#3]
[Link to cell](https://colab.research.google.com/drive/1SACbpeJvS1wrzozXAmIiXw8Kl3au-G68#scrollTo=ZTjbBC8EJR_y)

`<...>In basically any text corpus, there are a small number of very frequency tokens while most tokens appear fairly infrequently.<...>`

`very frequency` should be replaced with either `very high frequency` or `very frequent`.

**Comment by jakelever** [comment]
Thanks. Fixed. 1 point
