### ISSUE TITLE
Lab 3 Missing test

### ISSUE THREAD

**Issue by Bobi-V** [jakelever/textasdata_bugbounty#32]
![Screenshot 2024-01-23 164325](https://github.com/jakelever/textasdata_bugbounty/assets/102269110/b5c91d20-9895-485a-a089-d087157d0391)

Not entirely sure if there is no point for a test.

**Comment by jakelever** [comment]
Yep, there was supposed to be a test. I've added one in. Thanks for identifying this. 3 points
