### ISSUE TITLE
Lecture 6 - grammar

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#36]
[Slide 107](https://docs.google.com/presentation/d/1k1yNqLJkFNsw23psozgm4eQ9J3Uuxcwidqla75ctPqA/edit#slide=id.g10dde053f8b_0_1592)

> Example: What if worked at Bloomberg and wanted to extract company-risk relations from news archives?

Assuming you meant
> Example: What if **I** worked at Bloomberg and wanted to extract company-risk relations from news archives?

**Comment by jakelever** [comment]
Excellent. Thanks. 1 point
