### ISSUE TITLE
Lecture 4 mixed UK/US usage (between "categorization", "categorisation", "categorize")

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#36]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/6871e829-6d17-4323-8788-35750fcf0fff)
Slide 7 uses "categorization"

![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/cda48f71-9b5e-4aa5-ae98-710ee58f5699)
Slide 12 uses "categorisation"

![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/617cdd0a-4ff1-45e5-a98d-92540d7f9577)
Slide 13 uses "categorize"

**Comment by jakelever** [comment]
Yep. Let's go UK spelling. 1 point
