### ISSUE TITLE
Lab 3 mixed UK/US usage (between "modelling" and "modeling")

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#37]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/85ce2fa3-f1cc-4249-a377-cb6984451a2e)
There are 2 occurrences of "modeling" in the lab notebook. All other usages are "modelling".

**Comment by jakelever** [comment]
Yep, let's go UK spelling. Thanks. 1 point
