### ISSUE TITLE
Lab 3 potential missing test

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#38]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/77b2c072-f2fe-484c-b2b3-406967c74f88)
Not sure if intentional since it is a simple function, but there is no test for ```bigram_token_prob```

**Comment by jakelever** [comment]
Thanks for identifying that. I've added a labtest for it. 3 points as it was a missing part of the lab
