### ISSUE TITLE
Misleading error message for `tokenize_spacy` (Lab 1)

### ISSUE THREAD

**Issue by JahanKoninger** [jakelever/textasdata_bugbounty#4]
When returning a list of tokens from `tokenize_spacy()` instead of a list of strings, as required, the following error is returned:
`TypeError: Argument 'other' has incorrect type (expected spacy.tokens.token.Token, got str)`. This is the wrong way around, `str` is expected but `Token` is given. Image with further detail attached below:

![image](https://github.com/jakelever/textasdata_bugbounty/assets/97736594/d0f4f720-ca8c-4202-823c-5fb1ea910d42)

**Comment by jakelever** [comment]
Ah, an odd Spacy-related error message. This was a bit fiddly to fix so there is now some extra typechecking in labtest. Thanks for reporting and definitely could confuse others so 5 points
