### ISSUE TITLE
Lab 5 - tokenization - would be nice to have solutions!

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#41]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/69214642/220466869-041b17e9-b60e-40f8-9ffb-2ed15aa6cc8d.png">

this portion of the lab does not have solutions, and while one's working might look correct (based on the text explanation), it might be nice to have solutions to check!

(what I'm demonstrating with the photo is that additional arguments passed seem to still produce a result that is described by the next sentence though those arguments should not have been there)

**Comment by jakelever** [comment]
Hmm, you've managed to use `.encode_plus` which wasn't actually mentioned in the lab. I've decided to add in a mention of it and tidy up some of the language around that question. I think the described output should be enough to go on. So 1 point as you got me to make some changes.
