### ISSUE TITLE
Lab 5 - grammar

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#42]
[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=VMYYtAgjoH8y)

> However, case is sometimes important, so there is also bert-base-cased and other Transformer models may or may be case insensitive.

Should probably be

> However, case is sometimes important, so there is also bert-base-cased and other Transformer models **that** may or may **not** be case insensitive.

---

[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=tpgI1VeRIo5h)

> First we load one the pipeline for bert-base-uncased.

Not sure what you meant by "one", something is wrong with that sentence. Maybe

> First we load one **of** the pipeline**s** for bert-base-uncased.

---

[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=MavB50vnnSIS)

> Then we can use PyTorch's [cdist function](https://pytorch.org/docs/stable/generated/torch.cdist.html) **that that** calculates pair-wise distances between rows in a tensor.

that duplicated.

---

[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=XreICTXwX2D_)

> Then we could **get the context vector for match** by extracting the context vector with index 4.

Not sure what you meant here.

---

[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=YGDH4pu_ZCbk)

> Now let's compare context vectors for the word "match" across four sentences **where has** different meanings.

Should probably be

> Now let's compare context vectors for the word "match" across four sentences **where "match" has** different meanings.

**Comment by jakelever** [comment]
Excellent. Thanks for reporting all of these. 5 points
