### ISSUE TITLE
Lab 5 - broken link

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#43]
[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=V-ZhwaEWkXa-)

> Now let's get the context vector for the start token. We'll want to use some of the Pytorch tensor slicing that we learned at the end of the Tokenization section.[link text](https://)

Link leads to nowhere.

**Comment by jakelever** [comment]
Removed. Thanks. 1 point.
