### ISSUE TITLE
Lecture 4 Slide 30 Term (Word) Correction

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#44]
I believe it should be "train**ing** set" instead of calling the data "train set".
<img width="1032" alt="Screenshot 2024-01-29 at 11 50 46" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/90c961d7-3b16-4699-afc8-605d3f1b12c3">

**Comment by jakelever** [comment]
Yep. Thanks for submitting. 1 point
