### ISSUE TITLE
Lab 5 - incorrect distance type mentioned

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#44]
[Link to cell](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=qxY6n2KeoVgK)

> <...> the first and second vectors are the closest with a **cosine distance** of 0.3000 <...>

As you mention in the [previous paragraph](https://colab.research.google.com/drive/1iMwqZENREnu1nkXYMXMWyd8o8h43Ks-X#scrollTo=MavB50vnnSIS), and as is explained in the [pytorch docs](https://pytorch.org/docs/stable/generated/torch.cdist.html) and [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html), the default distance measure is Euclidean (Minkowski in general), not cosine.

**Comment by jakelever** [comment]
Thanks. Something that might confuse others. So 2 points
