### ISSUE TITLE
Lecture 4 Slide 33 Misspelling

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#45]
The sentence appears to say "To classifier" instead of "To classify" on bullet point #2.

<img width="688" alt="Screenshot 2024-01-29 at 11 57 55" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/e8b5cf9b-8dff-4661-82d3-f7291d7fde16">

**Comment by jakelever** [comment]
Yep, thanks. 1 point
