### ISSUE TITLE
Lab 1, Tokenization

### ISSUE THREAD

**Issue by ezad99** [jakelever/textasdata_bugbounty#5]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/76674776/8ca9d174-052d-41a9-a390-6ecc4983a6c4)
Not too sure about this but shouldn't tokenize_punctuation be tokenize_rulebased. Maybe it was intentional but it did confuse me at first glance when I was looking for a tokenize_puncuation function header

**Comment by jakelever** [comment]
You are indeed correct. Thanks for pointing this out. I've fixed this and 3 points as it could confuse others in the lab.
