### ISSUE TITLE
Lecture 7 -  explainable ai

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#51]
not quite an issue; perhaps more of a curious question (or maybe more explanation required in slides :D )

i understand that many people use shap to solve some limitations of lime; and shap has many visualization possibilities (as compared with lime). hence, may i ask why you had chosen lime > shap for nlp? 

thank you!

**Comment by jakelever** [comment]
Good question. I hadn't planned on going that far into explainability methods but you're right that it should be mentioned. A good thought. 4 points.
