### ISSUE TITLE
Lecture 6 - incorrect POS tag full name

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#52]
[Link to slide](https://docs.google.com/presentation/d/1k1yNqLJkFNsw23psozgm4eQ9J3Uuxcwidqla75ctPqA/edit#slide=id.g1114164314a_0_42)

In the provided table, one row says

| TAG | Name | Example|
| ------------- | ------------- |------------- |
| PROPN  | **adverb**  |Mary, Glasgow, HBO|

Name should be proper noun, not adverb.

**Comment by jakelever** [comment]
Good catch. Thanks. 2 points
