### ISSUE TITLE
Lecture 4 slide 43: "vectorisers", "vectorizing", "vectorized"

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#54]
<img width="311" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/f5c7884b-2cbe-4ba8-8280-0b7f24573259">

Slide 43 refers to "vectorisers" in the title, but slide 23 and 42 refer to "vectorizing"

<img width="298" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/95791552-aa23-4eba-b0dd-3f65a1d46e23">
<img width="588" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/949e38cd-3579-4b3a-a99d-ba98f9538d3c">

**Comment by jakelever** [comment]
Yeah, alright. A bit tricky as the API uses american english. We'll stick with the Z. 1 point
