### ISSUE TITLE
Coursework - sparse TF-IDF vectors

### ISSUE THREAD

**Issue by Franckevicius** [jakelever/textasdata_bugbounty#55]
>Write your own implementation of k-means clustering over **sparse** TF-IDF **vectors** of your dataset.

You probably meant *dense TF-IDF vectors*, or *sparse TF-IDF vector matrix*.

**Comment by jakelever** [comment]
Hey @Franckevicius, I had a think about this. I take "sparse vectors" to mean a vector that is mostly zeros. It doesn't specify which representation, though a sparse representation would be appropriate. A "dense TF-IDF vector" would mean a vector with mostly non-zero values across all the dimensions. It could be more specific, but "sparse vectors" is a common enough term when talking about mostly zero vectors, that I'm not going to change it. Thanks for making me think though.
