### ISSUE TITLE
Lecture 4 slide 21 capitalisation

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#57]
<img width="483" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/ef63895e-68f8-47f4-9ae6-2d1496800d48">

The start of the second half of this bullet point sentence should not be capitalised.

**Comment by jakelever** [comment]
Indeed. Thanks. Fixed. 1 point
