### ISSUE TITLE
Lecture 7 - Slide 29 - BERT

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#57]
(perhaps I'm the one with mis-conception about how BERT works)

how does the pipeline of "part of speech tagging" all the way till "relation classification" fit into the procedure of token embedding, segment embeddings, layer normalization, transformation etc?

and I thought there are 12 layers? so which are the other 4 on top of the 8 listed?

(i'm really on the fence about posting this because I don't know if it's just me who's not reading and understanding properly )

**Comment by jakelever** [comment]
Very good questions. I'm not sure these are bugs, but still interesting questions. I'll note them down as I may change that slide in the future.

- The idea is that BERT may be learning **implicitly** to do stages in a traditional NLP pipeline (e.g. POS tagging). That in doing its language tasks (e.g. masked language modelling), it is learning implicitly what a noun is, and what relations are. The way they test this is to only take the first k layers of the transformer. And see if the context vectors created after the k layers can be used for any of these tasks, while keeping the transformer frozen (not updating any weights). They appear to show that the earlier layers have already created context vectors that are good for POS tagging, while you have to wait until later layers for the more complex tasks.
- There were two original BERT model (BERT-base and BERT-large). BERT-base does indeed have 12 layers, but BERT-large has 24. This research was done using BERT-large. I guess they show up to 16 layers in that diagram as that's the largest bar in their barchart.
- Here's the paper in case you want to take a look: https://arxiv.org/pdf/1905.05950.pdf

**Comment by angelangweihan** [comment]
> Very good questions. I'm not sure these are bugs, but still interesting questions. I'll note them down as I may change that slide in the future.
> 
> * The idea is that BERT may be learning **implicitly** to do stages in a traditional NLP pipeline (e.g. POS tagging). That in doing its language tasks (e.g. masked language modelling), it is learning implicitly what a noun is, and what relations are. The way they test this is to only take the first k layers of the transformer. And see if the context vectors created after the k layers can be used for any of these tasks, while keeping the transformer frozen (not updating any weights). They appear to show that the earlier layers have already created context vectors that are good for POS tagging, while you have to wait until later layers for the more complex tasks.
> * There were two original BERT model (BERT-base and BERT-large). BERT-base does indeed have 12 layers, but BERT-large has 24. This research was done using BERT-large. I guess they show up to 16 layers in that diagram as that's the largest bar in their barchart.
> * Here's the paper in case you want to take a look: https://arxiv.org/pdf/1905.05950.pdf

Thanks @jakelever for the really concise explanation and the paper! I agree it's not a bug, and since my curiosity has been satiated, shall I close the issue?

**Comment by jakelever** [comment]
Yeah, feel free to close
