### ISSUE TITLE
Lab 5 - Comparing distance between match vectors

### ISSUE THREAD

**Issue by SamSJackson** [jakelever/textasdata_bugbounty#59]
I think there is an typo in the expected output in Lab 5 - Context Vectors & BERT.

Portion of lab: "Using context vectors of specific tokens"
In the question where we use the function `getContextVectorForToken`, we get a output matrix of:
![image](https://user-images.githubusercontent.com/86316114/222410968-b19b63c1-9c61-4e53-a304-d1aa8a1647e1.png)

It says that the expected farthest distance is `15.5223` but we have a larger distance of `15.6755`.
The smallest distances still match.

**Comment by jakelever** [comment]
You are absolutely correct. Thanks for pointing this out. 4 points as it may trip up someone.
