### ISSUE TITLE
Lecture 7 - Slide 70 - zero shot entity

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#61]
Q1: is the paper mentioned in the slides referring to the 2019 pre-print or the 2020 conf paper Scalable Zero-shot Entity Linking with Dense Entity Retrieval?

Q2: slides mentioned second stage as "Perform approximate “fuzzy” retrieval in dense vector space, score candidates." -> doesn't the second stage involve a cross-encoder that concatenates the cached items in stage 1 rather than a fuzzy retrieval? from what I understand (which might actually be entirely wrong), the math and the logical process behind the fuzzy retrieval and cross-encoder is slightly different

**Comment by jakelever** [comment]
Hi @angelangweihan, I put in the full citation to the EMNLP paper and you are absolutely correct on the methods. The description was not accurate for their two phase approach. Great catch! I'll say a single point for the citation and three points for the complexity of your second question. So 4 points.
