### ISSUE TITLE
Lecture 5 slide 20 suggested grammar fix

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#63]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/42210a0c-b37e-45a3-9ef4-38c0d6cdfe7d)
Since the point is referring to language models as a whole in plural, it should say "without needing to train them" rather than "without needing to train it"

**Comment by jakelever** [comment]
Yep, that'd be a challenge for a coreference resolution algorithm. Fixed and 1 point
