### ISSUE TITLE
Lecture 8 - Slide 51 - metric name

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#65]
"B-CUBED" / "B-Cubed" -> BCubed 
I assume you're referring to this BCubed? https://github.com/hhromic/python-bcubed

**Comment by jakelever** [comment]
Hmm, it seems to be commonly named "B-Cubed" and "B-CUBED" in the literature. The [original paper](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=ccdacc60d9d68dfc1f94e7c68bd56646c000e4ab) called it B-CUBED.
