### ISSUE TITLE
Lecture 8 - Slide 51 - potentially confusing

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#66]
This might not exactly be a bug (I'm just trying to make assumptions of what you're trying to express; which we won't know until tomorrow's lecture)

I assume you're trying to show why BCubed is the highly-preferred evaluation metric over other kinds of evaluation metric. Would it then be worth mentioning:
- set matching: % elements in true ref-chain, therefore changes in clusters not detected
- counting pairs: cluster has a quadratic dependence with the cluster size
- entropy: homogeneity or heterogeneity of the cluster does not affect the result
and that BCubed solves the above-mentioned constraints through the average of per-chain precision & recall?

Ref: A comparison of extrinsic clustering evaluation metrics based on formal constraints, 2008

**Comment by jakelever** [comment]
Hi Angela, very interesting points. I wasn't actually going to claim that B-Cubed is the preferred evaluation metrics as this is still debated by many. I'll make a note of these points for a future iteration of the the slides. Thanks!
