### ISSUE TITLE
lab 1 solution - error in regular expression

### ISSUE THREAD

**Issue by hara82** [jakelever/textasdata_bugbounty#7]
Possible bug in the last function in the solution file of lab1, in <Optional Extras> section.
This function apparently fails to remove suffix.
Thus, the result of stem_with_regex(['walked']) is still walked.
This function works correctly with input 'is,'

In my view, \w+ matches the entire word because matching "ed" has become optional with ? being attached to (ing|ed|s).
I tried to fix it by myself but could not make it.

**Comment by jakelever** [comment]
Nice catch. This is a tricky one. In this case I needed to use `\w+?` to match the stem instead of `\w`. The extra `?` tells the wildcard to be ungreedy and match the shortest stem it can (so that a suffix can be matched). 

So the fixed code is:
```python
def stem_with_regex(tokens):
  return  [ re.sub(r'^(is|\w+?)(ing|ed|s)?$',r'\1',t) for t in tokens ]
```

Nice one spotting this mistake. I'll say 2 points
