### ISSUE TITLE
Inconsistent Punctuation on Slide 56

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#70]
Some bullet points seem to end in full stops, whereas others do not in a seemingly random way.

Not entirely sure if there is a bottom level of pedantry capable here but _I'm gonna find it_.

<img width="682" alt="Screenshot 2024-02-05 at 19 39 21" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/99eac4ba-c4aa-455f-83d2-07461fcdbe41">

**Comment by jakelever** [comment]
Hmm, I don't think I'm going to start correcting this as there will need to be fixes everywhere and I need to draw a line somewhere. So 0 points
