### ISSUE TITLE
Lecture 2 - Slide 99 - complexity definition

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#71]
"Implementation is O(KN) instead of O(N2) for Hierarchical" -> do you mean O(2N) or O(N^2)? I believe what you had planned to type was O(N^2)? though literature says it's O(N^3)? (reason they had given was that in each merge, the dist between 2 clusters are calculated and then it needs to be stored - which makes sense).

**Comment by jakelever** [comment]
Agreed on all comments. Fixed
