### ISSUE TITLE
Lecture 4  - Slide 57 - Suggested improvement for clarity

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#73]
"Micro-averaging: Sum the like cells of the contingency tables across classes before calculating, e.g." -> "Micro-averaging: Sum the like cells of the contingency tables across all class before calculating metric score for any of the metrics"

"Macro-averaging: Calculate for each binary class and then take the average" -> "Macro-averaging: Calculate the metric score for each binary class then take the average"

aka showing the distinction between sum cells then calculate metric vs calculate metric then average

**Comment by jakelever** [comment]
Good comments. I'll add them to my notes for updating the slides next year
