### ISSUE TITLE
Lecture 6 - Slide 26 - Example

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#75]
why is "his £1300" O and B respectively and not B and I?

**Comment by jakelever** [comment]
Often for entity tags, you may not tag the entire noun-phrase - so possessive words, or some adjectives may be excluded. It's really down to the specific task in hand. In this case the "£1300" is the money entity and "his" is not included in it. For "his Macbook Pro", it's likely that only "Macbook Pro" would be tagged as a product.
