### ISSUE TITLE
Lecture 6 slide 49 inconsistent spacing

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#76]
<img width="292" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/b2abcf69-116c-4c35-9083-89b58bb77453">

There is a space on the left side of the pipe character for "P(V |N)" but not the right side.
There are no spaces for "P(DT|V)".

**Comment by jakelever** [comment]
Yep, fixed. Thanks. 1 point
