### ISSUE TITLE
Lecture 7 - Tail End of Slides

### ISSUE THREAD

**Issue by angelangweihan** [jakelever/textasdata_bugbounty#76]
You mentioned the following in the information extraction pipeline:
1. Named Entity Recognition - Detect and classify entities
2. Coreference resolution - Resolve pronouns to named entities
3. Entity Resolution (linking) - Ground entities to a representation of ‘world’ knowledge
4. Relation Extraction - Classify relationships between entities

And the slides following went
1. Named Entity Recognition
2. Entity Linking
3. Using synonyms from the knowledge base
4. Dense entity representations

Would you mind using the same terms and covering them in the same order? Less confusing for students!

**Comment by jakelever** [comment]
Good feedback. Thanks. Will go into my notes
