### ISSUE TITLE
Unclear definition of Distortion (L2. slide 90)

### ISSUE THREAD

**Issue by JakeTrevor** [jakelever/textasdata_bugbounty#77]
At the moment, the definition of distortion reads 
`Compute distortion = average sum squared distance of each point to its centroid`

This is quite ambiguous; it isn't clear if you mean
sum(distance^2) 
or
sum(distance)^2

It's also not clear why the words "average" and "sum" are both present - its not specified if you mean average sum for each centroid, or something else.

A proper equation would be nice/much clearer.

**Comment by jakelever** [comment]
Good point. The simpler way to describe it would be "average distance of each point to its centroid". Sum and average didn't really need to be in there.
