### ISSUE TITLE
Lab 5 UK/US mixed usage ("tokenization" / "tokenisation")

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#78]
<img width="170" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/87f036bb-85e7-49eb-adea-ca9b65ecb0db">

In the introductory paragraph of the lab, "tokenisation" is used once whereas "tokenization" is used everywhere else (4 occurrences).

**Comment by jakelever** [comment]
Yep, fixed this. Thanks. 1 point
