### ISSUE TITLE
Lecture 6 "bag of words" v.s. "bag-of-words"

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#79]
<img width="403" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/f06c38f1-e06f-465e-b913-581b653ef1d2">

On slide 3 and slide 107, "bag of words" is used

On slide 12, "bag-of-words" is used

<img width="776" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/82a75caa-26f2-4e70-9870-33fd5ad46515">

**Comment by jakelever** [comment]
Fixed. Good to be consistent. 1 point
