### ISSUE TITLE
Lecture 6 slide 30 missing word

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#80]
<img width="924" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/a77e063d-1e38-425f-ace7-aba8ddfa680a">

"sample manually labelled training sequences" should say "sample of manually labelled training sequences".

**Comment by jakelever** [comment]
Thanks. I changed up that slide as there was too much text. 1 point for flagging the issue
