### ISSUE TITLE
Lecture 6 Slide 55 Incorrect Calculation

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#83]
The third calculation, namely "P(VERB | PROPN) * P(drew | VERB) = 2/4 * 2/6 = 3/12" should instead use 3/6 instead of 2/6 as the probability for P(drew | VERB), as can be seen on the previous slide and the probabilities in the image below, making the answer 1/2, not 3/12. 

Also (just because I noticed), the answer for the third calculation as it is written currently should match the fourth calculation, since they use the same values, so should be 2/12, though this is obviously irrelevant since the third uses incorrect values.

<img width="686" alt="Screenshot 2024-02-12 at 19 29 55" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/177279bc-cfd0-4f51-81e2-3f262a1e293f">

**Comment by jakelever** [comment]
Thanks for spotting this. May trip someone up so 3 points. I've changed the denominators to make things more comparable anyway.
