### ISSUE TITLE
Lecture 6 Slide 71 Inconsistent Capitalisation

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#84]
Very pedantic, but "Noun Phrase" has both words capitalised vs "Verb phrase" and "Prepositional phrase". This is so minor I'm fine with 0 points for it. :)

<img width="679" alt="Screenshot 2024-02-12 at 19 51 46" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/592b5d21-d408-43e3-bd18-e482e71b0b6d">

**Comment by jakelever** [comment]
Yeah, this is a bit too minor. 0 points
