### ISSUE TITLE
Lecture 6 Slide 79 Incorrect Punctuation

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#85]
The sentence "In the most common case, every valid dependency graph has the following properties," should potentially have a colon (":") instead of a comma, since it's before the bullet points.

Also it may be better if the first bullet point was written as "undirected edges results in _a_ connected graph" instead of "undirected edges results in connected graph".

<img width="683" alt="Screenshot 2024-02-12 at 20 10 09" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/0f992db6-f418-4b7a-ad5b-032b352b38e6">

**Comment by jakelever** [comment]
Yep, colon makes more sense. 1 point
