### ISSUE TITLE
Assessed Coursework, Q2

### ISSUE THREAD

**Issue by ezad99** [jakelever/textasdata_bugbounty#86]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/76674776/26b58916-aa4d-4b69-9b5a-6304315ed5a4)

Question 2.1 seems a bit vague to me when it comes to the results that are intended to be shown. The initial question description says "For each question, pick the answer with the highest similarity score.". My understanding would be that we should get the similarity scores for every question in each set. We then we get the similarity score of each question and find the average among them. We can the use this in the report to compare between different similarity measures. Not sure if this is the intended outcome but I think it should be a bit more clear on what the question wants. This might also be applicable to Q3,Q4,Q5.

**Comment by jakelever** [comment]
Hi, it sounds like you may have misunderstood the question. I don't think I'll plan to reword it, as part of the task should be to figure out how to use the methods effectively to solve the QA problem. You could come to the lab / office hours. (0 points)
