### ISSUE TITLE
Lab 6 Inconsistent Phrase to Encode

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#87]
Sometimes the "." is missing from the phrase "I walked through Kelvingrove.", so is written as "I walked through Kelvingrove" during the lab, which doesn't seem to direct affect the output of any section, but could potentially be corrected for consistency.

The "tokenization" section is where this occurs most.

**Comment by jakelever** [comment]
Yep, this was a bit inconsistent and is a little more than a spelling mistake so 2 points.
