### ISSUE TITLE
Lecture 7 hyphenisation of model names

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#88]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/83447106-a7cc-4b15-bebd-0243af0c6d16)

Whenever GPT-4 is mentioned it is referred to without a hyphen, whereas GPT-3 is always referred to (correctly) with a hyphen.

**Comment by jakelever** [comment]
Good to be consistent. OpenAI seems to use a hyphen. So fixed and 1 point
