### ISSUE TITLE
Coursework Q1 Issue?

### ISSUE THREAD

**Issue by SamSJackson** [jakelever/textasdata_bugbounty#9]
This may just be a misunderstanding, so apologise if so. 

Our data is required to have more than 2 unique labels (and less than ten)
![image](https://user-images.githubusercontent.com/86316114/214856708-9cd9858c-b2d1-40e0-b9d5-45e6f300b741.png)

But further down the page, (part of Q1b), it is asked if we had to do preprocessing to obtain to make sure we had > 3 labels
![image](https://user-images.githubusercontent.com/86316114/214857080-168161be-bbde-425c-a3e0-973856f1bfc9.png)

Is this meant to be ">= 3"?

**Comment by jakelever** [comment]
Nice catch! You are correct. I've tidied up the language to use around. Because it's from the coursework, 3 points.
