### ISSUE TITLE
Lecture 2 slide 26 + slide 27 typos

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#9]
<img width="66" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/621a9923-0bdb-4547-a58d-57c492f06ed6">
<img width="71" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/6ab0b3ed-cb30-474a-8a97-6496e72bad04">

These should say "djokovic"

**Comment by jakelever** [comment]
While issue #10 reports the issue with the table, this issue notes it's also a mistake on slide 27. So 1 point for this issue too.
