### ISSUE TITLE
Lecture 7 Slide 7 Overlapping Image

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#93]
I believe the slide is static without animations, so some text is currently covered by the image.

<img width="839" alt="Screenshot 2024-02-19 at 11 33 50" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/dbc589a0-f391-4c2d-bd99-df485147c9f0">

**Comment by MrSpuddy** [comment]
This doesn't seem to occur when downloading the presentation as a PDF, though was visible on the Google Sheets online version, so will leave this up in case others experience it.

**Comment by jakelever** [comment]
How weird. I don't see this. Out of interest, what browser do you see this in?

**Comment by MrSpuddy** [comment]
I am using Safari on a MacBook, attached is a full screen image of what I see. I presume this is only affecting me for some reason, but still quite odd. It appears to display correctly on Chrome, so is indeed a Safari specific issue, even more weird...

<img width="1440" alt="Screenshot 2024-02-19 at 16 55 48" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/b0beb095-c9b9-4a2d-9763-b13dc8a872f2">

**Comment by jakelever** [comment]
Well, it's good to make sure it works for other people too. Thanks for reporting. I've resized one of the images so hopefully it won't happen again. Let's say 1 point as it was fairly minor
