### ISSUE TITLE
Lab 7 Minor Grammatical Correction

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#94]
From the "Visualising shift-reduce parsing" section, don't believe "And" should start a sentence, instead potentially using a comma instead of a full stop, and continuing the sentence on.

i.e "...as lists of tokens with their indices, and the list of edges..."

<img width="1011" alt="Screenshot 2024-02-20 at 09 31 30" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/e4941512-2ba9-4786-bb5d-f774a715da8d">

**Comment by jakelever** [comment]
Yep, we can fix that. I'm definitely not aiming for perfect grammatical and formal language in the labs. But still nice to fix little things. 1 points for this.
