### ISSUE TITLE
Lab 7 Broken Display Code

### ISSUE THREAD

**Issue by MrSpuddy** [jakelever/textasdata_bugbounty#95]
In the last section, "Using spaCy", the final part of code does not correctly run without adding the flag "jupyter=True" in Colab, as it prints out the raw svg code instead, as can be seen below in Image 1.

<img width="1065" alt="Screenshot 2024-02-20 at 09 56 45" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/e658ee41-c83f-4b2c-8b8e-6eb6198fb6f3">

<img width="1076" alt="Screenshot 2024-02-20 at 09 57 07" src="https://github.com/jakelever/textasdata_bugbounty/assets/79811864/98215e19-32b9-466c-b1c8-36821fb5f9cb">

**Comment by jakelever** [comment]
Yeah, this is a weird one as it seems to sometimes work. 3 points for pointing it out and giving a fix. Thanks
