### ISSUE TITLE
Lab 2 typo

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#96]
<img width="274" alt="image" src="https://github.com/jakelever/textasdata_bugbounty/assets/99495655/777d3f44-22b7-4767-9627-e925d6c00c45">

At the end of the last section of Lab 2.

"matrices" should say "matrix" here I believe

**Comment by jakelever** [comment]
Agreed. Fixed it. Thanks for reporting and 1 point
