### ISSUE TITLE
Lecture 8 slide 21 potential typo

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#98]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/04f42655-7910-4307-b57f-1b9433bcbf50)

I think this should say "isolate important tokens" since tokens of multiple paths may be considered important in a sentence?

**Comment by jakelever** [comment]
Indeed. Thanks for submitting. Fixed and 1 point
