### ISSUE TITLE
Lecture 8 slide 28 naming of entity resolution tools

### ISSUE THREAD

**Issue by JacksonDam** [jakelever/textasdata_bugbounty#99]
![image](https://github.com/jakelever/textasdata_bugbounty/assets/99495655/0879a0bf-8525-4618-959c-041c24082e0e)

I think that:
"Spacy" should be "spaCy" - https://spacy.io/
"TagMe" should be "TAGME" - https://tagme.d4science.org/tagme/
"DbPedia Spotlight" should be "DBpedia Spotlight" - https://www.dbpedia-spotlight.org/
"UMass Factorie" should be "UMass FACTORIE" - http://factorie.cs.umass.edu/

**Comment by jakelever** [comment]
Thanks for looking into this. Sorted and 1 point
